// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzySw6kI2FSOEBVQAEIj7wLv1imltZbeo',
    appId: '1:949094586503:web:173ea6406e7d29c5300022',
    messagingSenderId: '949094586503',
    projectId: 'flutter-chat-app-5d97e',
    authDomain: 'flutter-chat-app-5d97e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5d97e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCCX3OttvnPGnUvsBBt3JW0lgsoYdPT7A',
    appId: '1:949094586503:android:db6ecad346ab3e7e300022',
    messagingSenderId: '949094586503',
    projectId: 'flutter-chat-app-5d97e',
    storageBucket: 'flutter-chat-app-5d97e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeW-0Rgl_9CuOCTVd-e8zRBUOqK_9qQv0',
    appId: '1:949094586503:ios:1ff7af9073e3f5d5300022',
    messagingSenderId: '949094586503',
    projectId: 'flutter-chat-app-5d97e',
    storageBucket: 'flutter-chat-app-5d97e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeW-0Rgl_9CuOCTVd-e8zRBUOqK_9qQv0',
    appId: '1:949094586503:ios:4598eb147f25c9b8300022',
    messagingSenderId: '949094586503',
    projectId: 'flutter-chat-app-5d97e',
    storageBucket: 'flutter-chat-app-5d97e.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
